---
- name: Test bitbucket access
  shell: ping -c3 bitbucket.it.keysight.com

#- name: Allow sudo without password
#  lineinfile:
#    dest: /etc/sudoers
#    line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
#    validate: "visudo -cf %s"

- name: Check if git is installed
  package:
    name: git
    state: present
  check_mode: true
  register: git_check

- name: Check if curl is installed
  package:
    name: curl
    state: present
  check_mode: true
  register: curl_check

- name: Check if goss is installed
  stat:
    path: /usr/local/bin/goss
  register: goss_check

- name: Install git if not installed
  package:
    name: git
    state: present
  when: git_check.changed

- name: Install curl if not installed
  package:
    name: curl
    state: present
  when: curl_check.changed

- name: Install goss if not installed
  shell: |
    curl -L https://github.com/aelsabbahy/goss/releases/latest/download/goss-linux-amd64 -o /usr/local/bin/goss; \
    chmod +rx /usr/local/bin/goss
  when: goss_check.stat.exists == false
