- hosts: vmt
  pre_tasks:
    - name: Setup precondition
      import_role:
        name: precondition

  tasks:
    - name: Run goss audit
      import_role:
        name: goss
      tags:
        - goss
#    - name: Test reachability
#      shell: echo "I am $USER from $(hostname -I)"

  post_tasks:
    - name: Ensure postcondition
      import_role:
        name: postcondition
