- name: Set fact for Ubuntu20
  set_fact:
    git_url: "https://github.com/TNBL265/Ansible-Lockdown-Ubuntu20-Audit.git"
    branch: "dev"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

- name: Set fact for Amazon2
  set_fact:
    git_url: "https://bitbucket.it.keysight.com/scm/kps011/ansible-lockdown-amazon2-audit.git"
    branch: "dev"
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

- name: Set fact for RHEL 8
  set_fact:
    git_url: "https://bitbucket.it.keysight.com/scm/kps011/ansible-lockdown-rhel8-audit.git"
    branch: "dev"
  when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.0"

- name: Debug
  debug:
    msg: "Clone git from {{ git_url }}, branch {{ branch }}"

- name: Clone audit repo
  git:
    repo: "{{ git_url }}"
    dest: /var/tmp/ansible-lockdown
    single_branch: yes
    version: "{{ branch }}"

- name: Run goss audit
  shell: run_audit.sh
  args:
    chdir: /var/tmp/ansible-lockdown
  register:
    goss_out

- name: Debug json report
  debug:
    msg: "The json report name is {{ goss_out.stdout.find(.json) }}"

#- name: Copy back json report
#  copy:
#    src: goss_out.stdout.find(.json)
#    dest: {{ ansible_dir }}/json-report

- name: Remove audit repo
  file:
    path: /var/tmp/ansible-lockdown
    state: absent

- name: Remove json report
  file:
    path: "{{ goss_out.stdout.find(.json) }}"
    state: absent
