- name: Set fact for Ubuntu20
  set_fact:
    git_url: "https://github.com/TNBL265/Ansible-Lockdown-Ubuntu20-Audit.git"
    repo_dir: "Ansible-Lockdown-Ubuntu20-Audit"
    branch: "dev"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

- name: Set fact for Amazon2
  set_fact:
    git_url: "https://bitbucket.it.keysight.com/scm/kps011/ansible-lockdown-amazon2-audit.git"
    repo_dir: "ansible-lockdown-amazon2-audit"
    branch: "dev"
  when: ansible_distribution == "Amazon" and ansible_distribution_version == "2"

- name: Set fact for RHEL 8
  set_fact:
    git_url: "https://bitbucket.it.keysight.com/scm/kps011/ansible-lockdown-rhel8-audit.git"
    repo_dir: "ansible-lockdown-rhel8-audit"
    branch: "dev"
  when: ansible_distribution == "RedHat" and ansible_distribution_version == "8.0"

- name: Clone audit repo
  git:
    repo: "{{ git_url }}"
    dest: "/var/tmp/{{ repo_dir }}"
    single_branch: yes
    version: "{{ branch }}"

- name: Run goss audit
  shell: "/var/tmp/{{ repo_dir }}/run_audit.sh"
  register:
    goss_out

- name: Grep json report name
  shell: echo "{{ goss_out.stdout }}" | grep "/var/tmp/audit_ansible-lockdown-.*.json" -o
  register:
    json_out

- name: Copy back json report
  fetch:
    src: "{{ json_out.stdout }}"
    dest: "../json-report/{{ json_out.stdout }}/"
    flat: yes

- name: Remove audit repo
  file:
    path: "/var/tmp/{{ repo_dir }}"
    state: absent

- name: Remove json report
  file:
    path: "{{ json_out.stdout }}"
    state: absent
