---
- name: Remove git if not installed initially
  package:
    name: git
    state: absent
  when: git_check.changed

- name: Remove curl if not installed initially
  package:
    name: curl
    state: absent
  when: curl_check.changed

- name: Remove goss if not installed initially
  shell: rm -f /usr/local/bin/goss
  when: goss_check.stat.exists == false
